export const DEMO_JOBS = [
  {
    id: 'demo-1',
    title: 'Fix leaking pipe under kitchen sink',
    description: 'Have a slow leak under the kitchen sink that has been dripping for about a week. Need someone to come take a look and fix it. The shutoff valve works fine.',
    category: 'Plumbing',
    zip_code: '73401',
    status: 'open',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    profiles: { full_name: 'Mary Sutton' },
  },
  {
    id: 'demo-2',
    title: 'Install ceiling fan in master bedroom',
    description: 'Need a ceiling fan installed in my master bedroom. There is already a light fixture there so wiring should already be in place. I have the fan, just need someone to install it.',
    category: 'Electrical',
    zip_code: '73401',
    status: 'open',
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    profiles: { full_name: 'Dave Hollis' },
  },
  {
    id: 'demo-3',
    title: 'Mow and trim 2 acres of lawn',
    description: 'Looking for someone to mow and edge my property twice a month through the summer. About 2 acres, fairly flat. I have a riding mower you can use or bring your own.',
    category: 'Landscaping & Lawn Care',
    zip_code: '73434',
    status: 'open',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    profiles: { full_name: 'Beth Calloway' },
  },
  {
    id: 'demo-4',
    title: 'Repair section of wooden privacy fence',
    description: 'Three fence panels were knocked down in a recent storm. About 20 feet of 6-foot privacy fence needs to be re-set. Posts are still in good shape.',
    category: 'Fencing',
    zip_code: '73401',
    status: 'open',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    profiles: { full_name: 'Tom Brewer' },
  },
  {
    id: 'demo-5',
    title: 'HVAC tune-up before summer heat',
    description: 'Need annual maintenance on my central air unit before summer. System is about 7 years old and has never been serviced. Would also like Freon levels checked.',
    category: 'HVAC',
    zip_code: '73501',
    status: 'open',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    profiles: { full_name: 'Linda Marsh' },
  },
  {
    id: 'demo-6',
    title: 'Pressure wash house exterior and driveway',
    description: 'Two-story house with vinyl siding and a 2-car concrete driveway. Lots of mildew on the north side of the house. Estimating about 4 hours of work.',
    category: 'Cleaning Services',
    zip_code: '73434',
    status: 'open',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    profiles: { full_name: 'Randy Cole' },
  },
]
